config/Sfa.Tl.Find.Provider.Api.schema.json
Merging the Config schema to the pipeline branch to generate config.
=> Add configuration schema

azure-pipelines.yml, azure/findproviderapi-environmant.json
Removed API App Service as the API is hosted on Web App Service
=> cleaned Api App service

azure/findproviderapi-environment.json, yaml/jobs/findproviderapi-infrastructure-job.yml, yaml/jobs/findproviderapi-publish-site-job.yml
- Automate the binding of custom domain name and certificate to the App Service using the ARM template.
- Update variable, parameter and deployment names so there is clarity around what is being deployed.
=> Fully automate domain and certificate bindings

azure/findproviderapi-environment.json
Adding log analytics resource & workspace ID parameter
=> Migrate application insights to workspace based resources

azure/findproviderapi-environment.json, azure/findproviderapi-shared.json
removed commented out/unused resources and reformatted json
=> removed commented out resources and reformatted json

yaml/jobs/findproviderapi-build-application-job.yml, yaml/jobs/findproviderapi-post-deployment-job.yml, yaml/stages/findproviderapi-stage.yml
Added a new job for post deployment tasks.
Added the create github release task to the post deployment job.
=> moved github release create to post deployment

yaml/jobs/findproviderapi-post-deployment-job.yml
Added conditional to only run on the production stage
=> added prod only to github create condition

azure/findproviderapi-environment.json
Added swap slot app settings to check that staging slot is working correctly before performing swap slot.
=> added swap slot status checks

azure-pipelines.yml, azure/findproviderapi-environment.json, azure/findproviderapi-shared.json, yaml/jobs/findproviderapi-infrastructure-job.yml, yaml/jobs/findproviderapi-publish-dacpac-job.yml, yaml/jobs/findproviderapi-shared-infrastructure-job.yml, yaml/stages/findproviderapi-shared-stage.yml
- Added code changes to enable managed identity to send SQL server audit logs to storage account.
- Added code changes to create sql users automatically
=> added changes to managed identities

src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Qualifications.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed RouteQualification.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Routes.sql
Reverts SkillsFundingAgency/tl-find-provider-api#142
To be re added to develop branch once infrastructure changes have been merged into main branch.
=> Revert "added a new tlevel course"

src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Qualifications.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed RouteQualification.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Routes.sql
Reverts SkillsFundingAgency/tl-find-provider-api#144
Re adding to develop now that infra changes have been merged into main branch.
=> Revert "Revert "added a new tlevel course""

src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Qualifications.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed RouteQualification.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Routes.sql
Reverts SkillsFundingAgency/tl-find-provider-api#146
This is going to stay in the feature branch until the code is ready to be deployed to production.
=> "Revert "added a new tlevel course"

yaml/jobs/findproviderapi-generate-configs-job.yml, yaml/jobs/findproviderapi-infrastructure-job.yml
This PR is to remove unnecessary "show variable" tasks from the deploy infrastructure and generate config pipeline jobs.
=> Remove Show Variable Tasks

yaml/jobs/findproviderapi-publish-site-job.yml
This change updates the AzureRmWebAppDeployment task to use the most up to date version.
=> Update Web App Deployment Version

yaml/jobs/findproviderapi-infrastructure-job.yml, yaml/jobs/findproviderapi-shared-infrastructure-job.yml, yaml/stages/findproviderapi-shared-stage.yml
This pull request adds tasks to automate the configuration of Key Vault certificates and issuer settings.
**Changes**
- Adds a task to configure the certificate issuer/CA and contact information for Key Vault by utilising a PowerShell script from the DevOps Tools repo (https://github.com/DFE-Digital/operations-devops-tools/pull/31)
- Adds a task to update the certificate renewal policy for certificates to auto renew at 30 days expiry
=> Add Key Vault Config Automation to Pipeline

src/Sfa.Tl.Find.Provider.Web/Extensions/ApplicationBuilderExtensions.cs, src/Sfa.Tl.Find.Provider.Web/Program.cs
TL2023-867 add missing security headers
=> merge develop into main

src/Sfa.Tl.Find.Provider.Web/Extensions/ApplicationBuilderExtensions.cs
merge hotfix branch tl2023-917 restore header fix into develop
=> merge hotfix branch tl2023-917 restore header fix into develop

config/Sfa.Tl.Find.Provider.Api.schema.json, config/Sfa.Tl.Find.Provider.Web.schema.json, yaml/stages/findproviderapi-shared-stage.yml, yaml/stages/findproviderapi-stage.yml
This PR updates YAML configuration that is required to migrate secrets from pipeline variable groups to Key Vaults. It ensures that secrets are now stored in Key Vaults instead of directly in variable groups.
=> Update Variable Config for KV Secret Migration

src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Qualifications.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed RouteQualification.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Routes.sql, src/Sfa.Tl.Find.Provider.Application/Services/ProviderDataService.cs, src/Sfa.Tl.Find.Provider.Tests.Common/Builders/Models/RouteBuilder.cs
feature/tl2023 937 remove catering from options
=> Merge develop into master

src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Qualifications.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed RouteQualification.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Routes.sql, src/Sfa.Tl.Find.Provider.Application/Services/ProviderDataService.cs
included sales, marketing and procurement
=> included sales, marketing and procurement

src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Qualifications.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed RouteQualification.sql, src/Sfa.Tl.Find.Provider.Api.Database/PostDeployment/Seed Routes.sql, src/Sfa.Tl.Find.Provider.Application/Services/ProviderDataService.cs, yaml/jobs/findproviderapi-infrastructure-job.yml
included qualification Sales, Marketing and Procurement
=> merge develop into main 

yaml/jobs/findproviderapi-build-application-job.yml, yaml/jobs/findproviderapi-build-dacpac-job.yml, yaml/jobs/findproviderapi-generate-configs-job.yml, yaml/jobs/findproviderapi-infrastructure-job.yml, yaml/jobs/findproviderapi-post-deployment-job.yml, yaml/jobs/findproviderapi-publish-dacpac-job.yml, yaml/jobs/findproviderapi-publish-site-job.yml, yaml/jobs/findproviderapi-shared-infrastructure-job.yml
Update ADO pipelines to use latest supported Windows Server images, replacing deprecated 2019 version.
=> Update Windows Server 2019 to Latest in ADO Pipelines
